name: file_preview
description: A plug-in that supports flutter preview files
version: 1.1.8
homepage: https://github.com/gstory0404/file_preview

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.file_preview
        pluginClass: FilePreviewPlugin
      ios:
        pluginClass: FilePreviewPlugin
